defmodule Tunez.Repo.Migrations.UpdateVectors do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:albums) do
      modify :full_text_vector, :vector
      modify :vectorized_name, :vector
    end
  end

  def down do
    alter table(:albums) do
      modify :vectorized_name, :vector
      modify :full_text_vector, :vector
    end
  end
end
