defmodule Tunez.Repo.Migrations.RemoveThing do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tokens) do
      remove :id
    end

    execute("ALTER TABLE \"tokens\" ADD PRIMARY KEY (jti)")
  end

  def down do
    alter table(:tokens) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()")
    end

    execute("ALTER TABLE \"tokens\" ADD PRIMARY KEY (id, jti)")
  end
end
