defmodule Tunez.Repo.Migrations.AddMoreVectors do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:artists) do
      add :vectorized_name, :vector, size: 3072
      add :full_text_vector, :vector, size: 3072
    end
  end

  def down do
    alter table(:artists) do
      remove :full_text_vector
      remove :vectorized_name
    end
  end
end
