defmodule Tunez.Repo.Migrations.DoAThing do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:albums) do
      add :foo, :vector, size: 1523
    end
  end

  def down do
    alter table(:albums) do
      remove :foo
    end
  end
end
