defmodule Tunez.Repo.Migrations.AddDescriptionToAlbums do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:albums) do
      remove :foo
      add :description, :text
    end
  end

  def down do
    alter table(:albums) do
      remove :description
      add :foo, :vector, size: 1523
    end
  end
end
