defmodule Tunez.Repo.Migrations.RemoveIdFromTokens do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    WITH duplicate_tokens AS (
        SELECT jti
        FROM tokens
        GROUP BY jti
        HAVING COUNT(*) > 1
    ),
    revocation_tokens AS (
        SELECT t.jti
        FROM tokens t
        JOIN duplicate_tokens d ON t.jti = d.jti
        WHERE t.purpose = 'revocation' 
    ),
    other_tokens AS (
        SELECT t.*
        FROM tokens t
        JOIN duplicate_tokens d ON t.jti = d.jti
        WHERE t.jti NOT IN (SELECT jti FROM revocation_tokens)
    )
    DELETE FROM tokens
    WHERE jti IN (SELECT jti FROM other_tokens);
    """)

    alter table(:tokens) do
      remove :id
    end
  end

  def down do
    alter table(:tokens) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end
  end
end
