defmodule Tunez.Repo.Migrations.TrackFavorites do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:track_favorites, primary_key: false) do
      add :track_id,
          references(:tracks,
            column: :id,
            name: "track_favorites_track_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "track_favorites_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false
    end

    create index(:track_favorites, [:track_id])
  end

  def down do
    drop_if_exists index(:track_favorites, [:track_id])

    drop constraint(:track_favorites, "track_favorites_track_id_fkey")

    drop constraint(:track_favorites, "track_favorites_user_id_fkey")

    drop table(:track_favorites)
  end
end
